# audit_agent.py — VAYU Government-Grade Audit Brief Agent

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from datetime import datetime


def generate_audit_brief(forecast_data: dict, output_path="vayu_audit_brief.pdf"):

    doc  = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story  = []

    # Title
    title_style = ParagraphStyle("title", parent=styles["Heading1"],
                                 fontSize=16, textColor=colors.HexColor("#1a1a2e"),
                                 spaceAfter=6)
    sub_style   = ParagraphStyle("sub", parent=styles["Normal"],
                                 fontSize=10, textColor=colors.grey, spaceAfter=12)
    body_style  = ParagraphStyle("body", parent=styles["Normal"],
                                 fontSize=10, spaceAfter=8)

    story.append(Paragraph("VAYU - AI Forecast Audit Brief", title_style))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M IST')} | "
        f"Issued by: VAYU Orchestrator Agent | Regulator-ready", sub_style))
    story.append(Spacer(1, 0.3*cm))

    # Section 1: Forecast Summary
    story.append(Paragraph("1. Forecast Summary", styles["Heading2"]))
    summary_data = [
        ["Plant", "P10 (MW)", "P50 (MW)", "P90 (MW)", "Risk Score", "Alert"],
    ] + [
        [p["name"], p["p10"], p["p50"], p["p90"],
         f"{p['risk_score']}/10", p["alert"]]
        for p in forecast_data["plants"]
    ]

    t = Table(summary_data, colWidths=[4.5*cm, 2*cm, 2*cm, 2*cm, 2.5*cm, 2.5*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
        ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",    (0,0), (-1,-1), 9),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f0f4ff")]),
        ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#cccccc")),
        ("ALIGN",       (1,0), (-1,-1), "CENTER"),
        ("VALIGN",      (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",  (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4*cm))

    # Section 2: Anomaly Report
    story.append(Paragraph("2. Anomaly & Cascade Report", styles["Heading2"]))
    story.append(Paragraph(
        f"Alert Level: <b>{forecast_data['alert_level']}</b> | "
        f"Total Grid Drop: <b>{forecast_data['total_drop_mw']} MW</b> | "
        f"Plants Flagged: <b>{forecast_data['flagged_count']}</b>",
        body_style))

    # Section 3: SHAP Explanation
    story.append(Paragraph("3. Forecast Drivers (SHAP)", styles["Heading2"]))
    story.append(Paragraph(forecast_data["shap_explanation"], body_style))

    # Section 4: Learning Agent Status
    story.append(Paragraph("4. Model Health & Learning Agent", styles["Heading2"]))
    story.append(Paragraph(
        f"Average MAPE (last 7 days): <b>{forecast_data['avg_mape']}%</b> | "
        f"Drift Alerts: <b>{forecast_data['drift_alerts']}</b> | "
        f"Retrain Required: <b>{forecast_data['retrain_needed']}</b>",
        body_style))

    # Section 5: Decision Record
    story.append(Paragraph("5. Operator Decision Record", styles["Heading2"]))
    story.append(Paragraph(
        "This brief is auto-generated by VAYU for regulatory compliance. "
        "All forecasts include uncertainty bands (P10/P50/P90). "
        "Decisions made using this brief should be logged by the duty officer.",
        body_style))

    doc.build(story)
    print(f"Audit brief generated: {output_path}")
    return output_path
